language: python
python:
  - "2.7"
install: "pip install -r test-requirements.txt --use-mirrors"
# command to run tests
script: nosetests tests/unit tests/acception

branches:
  only:
    - master
    - develop

services:
  - elasticsearch
