language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r test-requirements.txt --use-mirrors"
# command to run tests
script: nosetests

branches:
  only:
    - master
    - develop

services:
  - elasticsearch
