#!/bin/bash

unit () {
    nosetests tests/unit -c .noserc
}

acception () {
    python setup.py install
    nosetests tests/acception --with-spec --spec-color
}

if [ $1 ]; then
    $1 $2 $3 $4 $5;
else
    echo  "   acception - runner acception tests"
    echo  "   unit - runner unit tests"
    exit 1
fi;

