#!/bin/bash

unit () {
    nosetests tests/unit -c .noserc --with-spec --spec-color
}

acceptance () {
    python setup.py install
    nosetests tests/acceptance  --with-spec --spec-color
}

clean () {
    find . -iname '*.pyc' -delete
}

if [ $1 ]; then
    $1 $2 $3 $4 $5;
else
    echo  "   acceptance - runner acceptance tests"
    echo  "   unit - runner unit tests"
    exit 1
fi;

